# Generated by Django 3.2 on 2021-05-23 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
