# Generated by Django 3.2 on 2021-05-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
    ]
