name: Build

on: push
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'

      - name: "Upgrading PIP"
        run: pip3 install --upgrade pip

      - name: "Installing the Dependencies"
        run: pip3 install -r requirements.txt

      - name: "Running Makemigrations"
        run: python3 manage.py makemigrations

      - name: "Running migrate"
        run: python3 manage.py migrate

      - name: "Testing"
        run: python3 manage.py test  

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'

      - name: "Upgrading PIP"
        run: pip3 install --upgrade pip

      - name: "Installing the Dependencies"
        run: pip3 install -r requirements.txt

      - name: "Testing"
        run: python3 manage.py test
      
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku HEAD:master -f